theme = "gruvbox"

[editor]
cursorline = true
rulers = [81]
bufferline = "multiple"
shell = ["sh", "-c"]

[editor.statusline]
mode.normal = "ğŸ“‘NOR"
mode.insert = "ğŸ“INS"
mode.select = "ğŸ•µï¸SEL"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"

[keys.insert]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
